## ----echo=FALSE, warning=FALSE, message=FALSE----------------------------------------------------------------------------------------------------
library(cluster)    # clustering algorithms
library(corrplot)
library(data.table)
library(dplyr)
library(DT)
library(EnvStats)
library(factoextra)
library(ggcorrplot)
library(ggplot2)
library(ggridges)
library(ggsignif)
library(ggthemes)
library(gridExtra)
library(heatmaply)
library(mapproj)
library(Matrix)
library(meta)
library(metafor)
library(multcompView)
library(plotly)
library(RColorBrewer)                           
library(readxl)
library(reshape2)
library(rmarkdown)
library(scales)
library(shinyBS)
library(stringr)
library(viridis)
library(waiter)

load("./initData/initData.Rdata")

